
CREATE TABLE public.group_students (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(255) NULL,
	CONSTRAINT group_students_pkey PRIMARY KEY (id)
);
CREATE TABLE public.student (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	first_name varchar(255) NULL,
	last_name varchar(255) NULL,
	group_id int4 NULL,
	CONSTRAINT student_pkey PRIMARY KEY (id),
	CONSTRAINT fk7jwmooaqkd5v6hgp9y7w7xygm FOREIGN KEY (group_id) REFERENCES public.group_students(id)
);


-- Insertion des classes
INSERT INTO group_students(id, name) VALUES
(1, '3A30'),
(2, '3A31'),
(3, '3A32'),
(4, '3A33'),
(5, '3A34');

-- Insertion des étudiants
INSERT INTO student(id, first_name, last_name, group_id) VALUES
-- Classe 1 : 7 étudiants
(1, 'Alice', 'Dupont', 1),
(2, 'Bob', 'Martin', 1),
(3, 'Charlie', 'Lemoine', 1),
(4, 'David', 'Moreau', 1),
(5, 'Emma', 'Petit', 1),
(6, 'Fanny', 'Roux', 1),
(7, 'George', 'Blanc', 1),

-- Classe 2 : 2 étudiants
(8, 'Hugo', 'Lefevre', 2),
(9, 'Isabelle', 'Garnier', 2),

-- Classe 3 : 5 étudiants
(10, 'Jean', 'Bernard', 3),
(11, 'Kevin', 'Noel', 3),
(12, 'Laura', 'Gomez', 3),
(13, 'Marie', 'Fabre', 3),
(14, 'Nicolas', 'Fontaine', 3),

-- Classe 4 : 4 étudiants
(15, 'Olivia', 'Baron', 4),
(16, 'Paul', 'Girard', 4),
(17, 'Quentin', 'Renard', 4),
(18, 'Romain', 'Perrin', 4),

-- Classe 5 : 3 étudiants
(19, 'Sarah', 'Marchand', 5),
(20, 'Thomas', 'Henry', 5),
(21, 'Ulysse', 'Simon', 5);
